### ISSUE TITLE
Can't get Content-Type of application/json

### ISSUE THREAD

**Issue by jmccann** [Jesse0Michael/go-rest-assured#5]
Given I use a json file of the following to preload from:

```
[
  {
    "path": "test/json",
    "method": "GET",
    "status_code": 200,
    "delay": 0,
    "response": "{\"test\":\"abc123\"}",
    "headers": {
      "Content-Type": "application/json"
    }
  }
]
```

When I hit `when/test/json` I get `Content-Type: text/plain; charset=utf-8`.  I expected to get `Content-Type: application/json`.

```
» curl -v http://localhost:8080/when/test/json                                 
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /when/test/json HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Date: Mon, 04 Jun 2018 17:22:34 GMT
< Content-Length: 17
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
{"test":"abc123"}%                                                              
```

Let me know if I'm just doing something wrong.  😉

**Comment by Jesse0Michael** [comment]
Hey! This is exciting, my first ever open-source, cooperative experience!

Thanks for checking out this repo and making it better! 

If there's any other issues that you run into, or features you wish were included, or ways that you think something should be done differently, let me know!! I would love to see this tool become better and more useful!

**Comment by jmccann** [comment]
haha, congrats on that.  🎊
